# Generated by Django 2.2.10 on 2021-07-01 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choiceanswer',
            options={'verbose_name': 'Ответ для выбора', 'verbose_name_plural': 'Ответы для выбора'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(verbose_name='ID пользователя')),
                ('answer', models.TextField(blank=True, help_text='Ответ пользователя в виде текста', verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Question', verbose_name='Вопрос')),
                ('selected_answers', models.ManyToManyField(blank=True, to='polls.ChoiceAnswer', verbose_name='Выбранные пользователем ответы')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
